---

- name: upgrade system and packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
    purge: yes
    autoclean: yes
  register: __upgrade_complete_result

- name: create upgrade_complete var
  set_fact:
    upgrade_completed: "{{ __upgrade_complete_result.changed }}"

- name: disable unwanted services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: False
  when: upgrade_debian_disable_timers
  loop:
    - apt-daily.service
    - apt-daily.timer
    - apt-daily-upgrade.timer
    - apt-daily-upgrade.service
