---

- name: 'upgrade system'
  command: syspatch
  register: __upgrade_syspatch_status
  changed_when: >
    __upgrade_syspatch_status.stdout
    and __upgrade_syspatch_status.rc == 0
  failed_when: __upgrade_syspatch_status.rc != 0

- name: 'upgrade packages'  # noqa 403
  openbsd_pkg:
    name: '*'
    state: 'latest'
  register: __upgrade_pkg_complete_result

- name: 'create upgrade_complete var'
  set_fact:
    upgrade_completed: "{{ __upgrade_pkg_complete_result.changed or (__upgrade_syspatch_status.stdout and __upgrade_syspatch_status.rc == 0) }}"
