---

- hosts: all
  name: 'Converge'
  become: True

  tasks:
    - import_role:
        name: 'ansible-role-upgrade'
      vars:
        upgrade_completed_then_reboot: False
        upgrade_debian_disable_timers: False
