---

- hosts: all
  name: 'Converge'
  become: True

  tasks:
    - import_role:
        name: 'ansible-role-upgrade'
      vars:
        upgrade_completed_then_reboot: ansible_facts['virtualization_type'] != 'docker'
